services:
  frontend:
    build:
      context: ./frontend  # Path to your frontend app's Dockerfile
    container_name: air-ticket-frontend
    ports:
      - "3000:3000"  # The frontend app runs on port 3000
    volumes:
      - ./frontend:/app  # Mount the frontend source code as a volume
    depends_on:
      - backend

  backend:
    build:
      context: ./backend  # Path to your backend app's Dockerfile
    container_name: air-ticket-backend
    ports:
      - "5000:5000"  # Backend runs on port 5000
    environment:
      - MONGO_URI=mongodb+srv://air:air@airplane.wwvwd.mongodb.net/?retryWrites=true&w=majority&appName=Airplane
    volumes:
      - ./backend:/app  # Mount the backend source code as a volume
    depends_on:
      - frontend
    stdin_open: true
    tty: true

