version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Path to your frontend app's Dockerfile
    ports:
      - "3000:3000"  # The frontend app runs on port 3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend  # Path to your backend app's Dockerfile
    ports:
      - "5000:5000"  # Backend runs on port 5000
    environment:
      - MONGO_URI=mongodb+srv://air:air@airplane.wwvwd.mongodb.net/?retryWrites=true&w=majority&appName=Airplane
    depends_on:
      - frontend

